---
id: isocjp-ietf-116-report
base_name: slide
tags: ['ietf', 'isocjp']
presentation_date: "2023-05-25"
presentation_start_time:
presentation_end_time:
version: 1.0.0
licenses: ["MIT"]
slideshare_id:
speaker_deck_id:
vimeo_id:
youtube_id:
width: 1920
height: 1080
author:
  markup_language: :markdown
  name: unasuke
  email: yusuke194525@gmail.com
  rubygems_user: unasuke
  slideshare_user:
  speaker_deck_user:
source_code_url: https://github.com/unasuke/isocjp-ietf-116-report
